// https://developer.bitcoin.org/reference/rpc/index.html
let RpcMethodEnum = {
  BlockchainRPCs:{
    getbestblockhash: "getbestblockhash",
    getblock: "getblock",
    getblockchaininfo: "getblockchaininfo",
    getblockcount: "getblockcount",
    getblockfilter: "getblockfilter",
    getblockhash: "getblockhash",
    getblockheader: "getblockheader",
    getblockstats: "getblockstats",
    getchaintips: "getchaintips",
    getchaintxstats: "getchaintxstats",
    getdifficulty: "getdifficulty",
    getmempoolancestors: "getmempoolancestors",
    getmempooldescendants: "getmempooldescendants",
    getmempoolentry: "getmempoolentry",
    getmempoolinfo: "getmempoolinfo",
    getrawmempool: "getrawmempool",
    gettxout: "gettxout",
    gettxoutproof: "gettxoutproof",
    gettxoutsetinfo: "gettxoutsetinfo",
    preciousblock: "preciousblock",
    pruneblockchain: "pruneblockchain",
    savemempool: "savemempool",
    scantxoutset: "scantxoutset",
    verifychain: "verifychain",
    verifytxoutproof: "verifytxoutproof",
  },
  ControlRPCs:{
    getmemoryinfo:"getmemoryinfo",
    getrpcinfo:"getrpcinfo",
    help:"help",
    logging:"logging",
    stop:"stop",
    uptime:"uptime",
  },
  GeneratingRPCs:{
    generateblock: "generateblock",
    generatetoaddress: "generatetoaddress",
    generatetodescriptor: "generatetodescriptor",
  },
  MiningRPCs:{
    getblocktemplate: "getblocktemplate",
    getmininginfo: "getmininginfo",
    getnetworkhashps: "getnetworkhashps",
    prioritisetransaction: "prioritisetransaction",
    submitblock: "submitblock",
    submitheader: "submitheader",
  },
  NetworkRPCs:{
    addnode: "addnode",
    clearbanned: "clearbanned",
    disconnectnode: "disconnectnode",
    getaddednodeinfo: "getaddednodeinfo",
    getconnectioncount: "getconnectioncount",
    getnettotals: "getnettotals",
    getnetworkinfo: "getnetworkinfo",
    getnodeaddresses: "getnodeaddresses",
    getpeerinfo: "getpeerinfo",
    listbanned: "listbanned",
    ping: "ping",
    setban: "setban",
    setnetworkactive: "setnetworkactive",
  },
  RawtransactionsRPCs: {
    analyzepsbt: "analyzepsbt",
    combinepsbt: "combinepsbt",
    combinerawtransaction: "combinerawtransaction",
    converttopsbt: "converttopsbt",
    createpsbt: "createpsbt",
    createrawtransaction: "createrawtransaction",
    decodepsbt: "decodepsbt",
    decoderawtransaction: "decoderawtransaction",
    decodescript: "decodescript",
    finalizepsbt: "finalizepsbt",
    fundrawtransaction: "fundrawtransaction",
    getrawtransaction: "getrawtransaction",
    joinpsbts: "joinpsbts",
    sendrawtransaction: "sendrawtransaction",
    signrawtransactionwithkey: "signrawtransactionwithkey",
    testmempoolaccept: "testmempoolaccept",
    utxoupdatepsbt: "utxoupdatepsbt",
  },
  UtilRPCs:{
    createmultisig: "createmultisig",
    deriveaddresses: "deriveaddresses",
    estimatefee: "estimatefee",
    estimatesmartfee: "estimatesmartfee",
    getdescriptorinfo: "getdescriptorinfo",
    getindexinfo: "getindexinfo",
    signmessagewithprivkey: "signmessagewithprivkey",
    validateaddress: "validateaddress",
    verifymessage: "verifymessage",
  },
  WalletRPCs:{
    abandontransaction: "abandontransaction",
    abortrescan: "abortrescan",
    addmultisigaddress: "addmultisigaddress",
    backupwallet: "backupwallet",
    bumpfee: "bumpfee",
    createwallet: "createwallet",
    dumpprivkey: "dumpprivkey",
    dumpwallet: "dumpwallet",
    encryptwallet: "encryptwallet",
    getaddressesbylabel: "getaddressesbylabel",
    getaddressinfo: "getaddressinfo",
    getbalance: "getbalance",
    getbalances: "getbalances",
    getnewaddress: "getnewaddress",
    getrawchangeaddress: "getrawchangeaddress",
    getreceivedbyaddress: "getreceivedbyaddress",
    getreceivedbylabel: "getreceivedbylabel",
    gettransaction: "gettransaction",
    getunconfirmedbalance: "getunconfirmedbalance",
    getwalletinfo: "getwalletinfo",
    importaddress: "importaddress",
    importdescriptors: "importdescriptors",
    importmulti: "importmulti",
    importprivkey: "importprivkey",
    importprunedfunds: "importprunedfunds",
    importpubkey: "importpubkey",
    importwallet: "importwallet",
    keypoolrefill: "keypoolrefill",
    listaddressgroupings: "listaddressgroupings",
    listlabels: "listlabels",
    listlockunspent: "listlockunspent",
    listreceivedbyaddress: "listreceivedbyaddress",
    listreceivedbylabel: "listreceivedbylabel",
    listsinceblock: "listsinceblock",
    listtransactions: "listtransactions",
    listunspent: "listunspent",
    listwalletdir: "listwalletdir",
    listwallets: "listwallets",
    loadwallet: "loadwallet",
    lockunspent: "lockunspent",
    psbtbumpfee: "psbtbumpfee",
    removeprunedfunds: "removeprunedfunds",
    rescanblockchain: "rescanblockchain",
    send: "send",
    sendmany: "sendmany",
    sendtoaddress: "sendtoaddress",
    sethdseed: "sethdseed",
    setlabel: "setlabel",
    settxfee: "settxfee",
    setwalletflag: "setwalletflag",
    signmessage: "signmessage",
    signrawtransactionwithwallet: "signrawtransactionwithwallet",
    unloadwallet: "unloadwallet",
    upgradewallet: "upgradewallet",
    walletcreatefundedpsbt: "walletcreatefundedpsbt",
    walletlock: "walletlock",
    walletpassphrase: "walletpassphrase",
    walletpassphrasechange: "walletpassphrasechange",
    walletprocesspsbt: "walletprocesspsbt",
  }
}

module.exports = {
  RpcMethodEnum,
};